version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - ./data:/data
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT" # Optional for Bukkit/Plugin support
      SEED: SampleSeed
      OPS: "SampleUserName"
      BUILD_FROM_SOURCE: true
      MOTD: "Message of the day"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 50
      MAX_MEMORY: 8G # optional, default is 1G
      SERVER_NAME: "ServerName"
    tty: true
    stdin_open: true
    restart: unless-stopped
